# Generated by Django 3.2 on 2024-03-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100, verbose_name='College Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Id')),
                ('mobile', models.CharField(max_length=30, verbose_name='Mobile Num')),
                ('accommodation_fee', models.CharField(max_length=300, verbose_name='Accommodation Fee')),
                ('eligibility', models.CharField(max_length=300, verbose_name='Eligibility')),
                ('placement', models.TextField(max_length=2000, verbose_name='Placement Opportunity')),
                ('scholarship_scheme', models.TextField(max_length=2000, verbose_name='Scholarship Scheme')),
                ('rules', models.TextField(max_length=2000, verbose_name='Rules and Regulations')),
                ('image', models.FileField(null=True, upload_to='product/', verbose_name='College Image')),
                ('course', models.TextField(max_length=3000, verbose_name='Course')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Username')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=300, verbose_name=' City')),
                ('address', models.TextField(max_length=2000, verbose_name=' Address')),
                ('notes', models.TextField(max_length=3000, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('email_id', models.EmailField(max_length=255, verbose_name='Email Id')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('education', models.CharField(max_length=200, verbose_name='Education')),
                ('Score', models.CharField(max_length=200, verbose_name='Score')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('state', models.CharField(default='Tamil Nadu', max_length=100, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Student Image')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('option1', models.CharField(max_length=255, verbose_name='Option1')),
                ('option2', models.CharField(max_length=255, verbose_name='Option2')),
                ('option3', models.CharField(max_length=255, verbose_name='Option3')),
                ('option4', models.CharField(max_length=255, verbose_name='Option4')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question_category')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.college_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(null=True)),
                ('rand_num', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=255, verbose_name='Answer')),
                ('status', models.CharField(choices=[('', 'Select'), ('pending', 'Pending'), ('publish', 'Publish')], max_length=30, null=True, verbose_name='Publish Answer')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question_category')),
                ('college_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.college_detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_detail')),
            ],
        ),
    ]
