# Generated by Django 3.2 on 2024-03-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255, verbose_name='12th Mark')),
                ('certificate', models.FileField(upload_to='documents/', verbose_name='Upload Certificate')),
                ('aadhaar', models.CharField(blank=True, max_length=50, null=True)),
                ('community', models.CharField(max_length=255)),
                ('commun', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Community')),
                ('proof', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Aadhaar')),
                ('status', models.CharField(blank=True, choices=[('', 'Select'), ('test', 'Take Test'), ('rejected', 'Rejected')], max_length=30, null=True, verbose_name='Status')),
                ('test_status', models.CharField(blank=True, choices=[('', 'Select'), ('taken', 'Test Taken'), ('not', 'Not Yet')], max_length=30, null=True, verbose_name='Test Status')),
                ('sheet', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sheet Confirmed')),
                ('amount', models.CharField(blank=True, max_length=30, null=True, verbose_name='Amount')),
                ('documents', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Document Should Carry')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question_category')),
                ('college_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.college_detail')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student_detail')),
            ],
        ),
    ]
